In [1]:
import numpy as np

In [2]:
str1='ABCABCBA'
str2='CBABCABCC'
len1=len(str1)
len2 = len(str2)
arr = np.zeros((len1+1,len2+1),dtype=np.int)

In [3]:
#LCS演算法矩陣建造
for i in range(len1):
    for j in range(len2):
        if(str1[i]==str2[j]):
            arr[i+1][j+1]=arr[i][j]+1
        else:
            if(arr[i+1][j]>arr[i][j+1]):
                arr[i+1][j+1]=arr[i+1][j]
            else:
                arr[i+1][j+1]=arr[i][j+1]
                

In [4]:
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 1 1 1]
 [0 0 1 1 2 2 2 2 2 2]
 [0 1 1 1 2 3 3 3 3 3]
 [0 1 1 2 2 3 4 4 4 4]
 [0 1 2 2 3 3 4 5 5 5]
 [0 1 2 2 3 4 4 5 6 6]
 [0 1 2 2 3 4 4 5 6 6]
 [0 1 2 3 3 4 5 5 6 6]]


In [5]:
#LCS回溯-找出LCS序列
string=''
#num 是 LCS字元
num=arr[len1][len2]
# a1 a2 用來追蹤矩陣位置
a1=len1
a2=len2
# 紀錄 LCS走位
motion=[]
# 紀錄 str1 str2 字串 (含gap)
str1Lcs=''
str2Lcs=''
while num>0:
    if str1[a1-1]==str2[a2-1]:
        a1=a1-1
        a2=a2-1
        string=str1[a1]+string
        num=arr[a1][a2]
        motion.append('middle')
        str1Lcs=str1[a1]+str1Lcs
        str2Lcs=str1[a1]+str2Lcs
    else:
        if arr[a1-1][a2]>=arr[a1][a2-1]:
            a1=a1-1
            motion.append('height')
            str1Lcs=str1[a1]+str1Lcs
            str2Lcs='_'+str2Lcs
        else:
            a2=a2-1
            motion.append('left')
            str1Lcs='_'+str1Lcs
            str2Lcs=str2[a1]+str2Lcs

In [7]:
print('共同子序列LCS:'+string)
#print(len(motion))
print('LCS gap:')
print('str1:'+str1Lcs)
print('str2:'+str2Lcs)
print()
print('移動方式:')
for i in range(len(motion)):
    print(motion[i])

共同子序列LCS:ABCABC
LCS gap:
str1:ABCAB_CBA
str2:ABCABAC__

移動方式:
height
height
middle
left
middle
middle
middle
middle
middle


In [8]:
#創建 LCS 位置移動圖--20190808撰寫
LCSarray=[]
for i in range(2*len1+1):
    a=''
    if i%2==0:
        for j in range(2*len2+1):
            if j%2==0:
                a=a+(str(arr[int(i/2)][int(j/2)]))
            else:
                a=a+' '
    else:
        for j in range(2*len2+1):
            a=a+' '
    LCSarray.append(a)
for i in LCSarray:
    print(i)


0 0 0 0 0 0 0 0 0 0
                   
0 0 0 1 1 1 1 1 1 1
                   
0 0 1 1 2 2 2 2 2 2
                   
0 1 1 1 2 3 3 3 3 3
                   
0 1 1 2 2 3 4 4 4 4
                   
0 1 2 2 3 3 4 5 5 5
                   
0 1 2 2 3 4 4 5 6 6
                   
0 1 2 2 3 4 4 5 6 6
                   
0 1 2 3 3 4 5 5 6 6


In [9]:
#LCS移動圖--箭頭放置
LCSarrayLen1=2*len1
LCSarrayLen2=2*len2
for i in motion:
    if i=='middle':
        LCSarrayLen1=LCSarrayLen1-1
        LCSarrayLen2=LCSarrayLen2-1
        temp=list(LCSarray[LCSarrayLen1])
        temp[LCSarrayLen2]='↖'
        LCSarray[LCSarrayLen1]=''.join(temp)
        LCSarrayLen1=LCSarrayLen1-1
        LCSarrayLen2=LCSarrayLen2-1
    elif i=='left':
        LCSarrayLen2=LCSarrayLen2-1
        temp=list(LCSarray[LCSarrayLen1])
        temp[LCSarrayLen2]='←'
        LCSarray[LCSarrayLen1]=''.join(temp)
        LCSarrayLen2=LCSarrayLen2-1
    else:
        LCSarrayLen1=LCSarrayLen1-1
        temp=list(LCSarray[LCSarrayLen1])
        #print(temp,len(temp),LCSarrayLen2)
        
        temp[LCSarrayLen2]='↑'
        LCSarray[LCSarrayLen1]=''.join(temp)
        LCSarrayLen1=LCSarrayLen1-1

In [10]:
for i in LCSarray:
    print(i)

0 0 0 0 0 0 0 0 0 0
     ↖             
0 0 0 1 1 1 1 1 1 1
       ↖           
0 0 1 1 2 2 2 2 2 2
         ↖         
0 1 1 1 2 3 3 3 3 3
           ↖       
0 1 1 2 2 3 4 4 4 4
             ↖     
0 1 2 2 3 3 4 5←5 5
                 ↖ 
0 1 2 2 3 4 4 5 6 6
                  ↑
0 1 2 2 3 4 4 5 6 6
                  ↑
0 1 2 3 3 4 5 5 6 6
