In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
from torch.autograd import Variable
import torchvision
from torchvision import datasets, models, transforms
import time
import os
from PIL import Image
model = torch.load('model2.pkl',map_location='cpu')

In [25]:
# data_transforms =transforms.Compose([
#             transforms.Scale(256),
#             transforms.CenterCrop(224),
#             transforms.ToTensor(),
#             transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
#         ])
# from PIL import Image
# im = Image.open('0e96ddb45429ee0c81d55bb33f500894.jpg')
# print(im)
# image_data=data_transforms(im)
# image_data=image_data.unsqueeze(dim=0)
# #image_data=image_data.cuda()#把image_data放入GPU
# #image_data2 = torch.utils.data.DataLoader(image_data,batch_size=4,shuffle=True,num_workers=4) 


# y=model(image_data)
# print(y)
# y=y.cpu()#把y放回cpu
# print(y.data.numpy())

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1059x1500 at 0x53C1668>
tensor([[0.0847, 0.1086]], grad_fn=<AddmmBackward>)
[[0.08472833 0.10859007]]


In [26]:
import os
piclist = os.listdir('./picture/')
for i in range(0,len(piclist)):
    piclist[i] = './picture/'+piclist[i]
    rel = os.path.abspath(piclist[i])
    rel=rel.replace('\\','/')
    piclist[i]=rel
print(rel)
    

D:/python_Test/python-design/pytorch/picture/1504128_340738532770639_3083963326714400701_n (1).jpg


In [2]:
#單一使用
from PIL import Image
import requests
from io import BytesIO
data_transforms =transforms.Compose([
            transforms.Scale(256),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])
pic=requests.get('https://t1.wnacg.download/data/t/0535/90/15298648573876.png').content
im = Image.open(BytesIO(pic))
image_data=data_transforms(im)
image_data=image_data.unsqueeze(dim=0)
y=model(image_data)
print(y.data.numpy())


D:\anaconda\lib\site-packages\torchvision\transforms\transforms.py:207: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  warnings.warn("The use of the transforms.Scale transform is deprecated, " +


RuntimeError: output with shape [1, 224, 224] doesn't match the broadcast shape [3, 224, 224]

In [27]:
data_transforms =transforms.Compose([
            transforms.Scale(256),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])
num=0
total=len(piclist)
for i in piclist:
    im = Image.open(i)
    image_data=data_transforms(im)
    image_data=image_data.unsqueeze(dim=0)
    y=model(image_data)
    value = y.data.numpy()
    if (value[0,0]-value[0,1])<0:
        num+=1
print(num,total,num/total)

0 3 0.0


In [5]:
w=y.data.numpy()
print(w)
if w[0,0]>0:
    label='NO'
else:
    lavber='Yes'
print(label)

[[0.08472833 0.10859007]]
NO
