In [4]:
str1='aaabbbccc'
str2='aaacbbcc'
len1=len(str1)
len2 = len(str2)

In [11]:
import numpy as np
arr = np.zeros((len1+1,len2+1),dtype=np.int)

In [12]:
print(arr)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [20]:
for i in range(len1):
    for j in range(len2):
        if(str1[i]==str2[j]):
            arr[i+1][j+1]=arr[i][j]+1
        else:
            if(arr[i+1][j]>arr[i][j+1]):
                arr[i+1][j+1]=arr[i+1][j]
            else:
                arr[i+1][j+1]=arr[i][j+1]
                

In [21]:
print(arr)

[[0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1]
 [0 1 2 2 2 2 2 2 2]
 [0 1 2 3 3 3 3 3 3]
 [0 1 2 3 3 4 4 4 4]
 [0 1 2 3 3 4 5 5 5]
 [0 1 2 3 3 4 5 5 5]
 [0 1 2 3 4 4 5 6 6]
 [0 1 2 3 4 4 5 6 7]
 [0 1 2 3 4 4 5 6 7]]


In [24]:

string=''
num=arr[len1][len2]
a1=len1
a2=len2
while num>0:
    if str1[a1-1]==str2[a2-1]:
        a1=a1-1
        a2=a2-1
        string=str1[a1]+string
        num=arr[a1][a2]
    else:
        if arr[a1-1][a2]>arr[a1][a2-1]:
            a1=a1-1
        else:
            a2=a2-1
    
        

In [25]:
print(string,)

aaabbcc
